### ISSUE TITLE
The app opens and closes for some time after selecting Bandcamp

### ISSUE THREAD

**Issue by Dilmen** [XiangRongLin/NewPipe-preuinified#2]
First of all, thank you for your support.

English isn't my first language.

On 0.21.0, I selected Bandcamp in the service, and the app returned me a crash error with the UI type. I upgraded to 21.1.1 and now this is happening (video).

https://user-images.githubusercontent.com/16386382/114614034-8cb91f00-9c93-11eb-8749-0025ee326f3b.mp4

Checked on another device, the bug is present.

Information from adb

> E( 5829: 5829) FATAL EXCEPTION: main
E( 5829: 5829) Process: org.schabi.newpipe.preunified, PID: 5829
E( 5829: 5829) java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe.preunified/org.schabi.newpipe.report.ErrorActivity}: android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called CREATOR on class org.schabi.newpipe.report.ErrorActivity$ErrorInfo
E( 5829: 5829) 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
E( 5829: 5829) 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
E( 5829: 5829) 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
E( 5829: 5829) 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
E( 5829: 5829) 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
E( 5829: 5829) 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
E( 5829: 5829) 	at android.os.Handler.dispatchMessage(Handler.java:107)
E( 5829: 5829) 	at android.os.Looper.loop(Looper.java:213)
E( 5829: 5829) 	at android.app.ActivityThread.main(ActivityThread.java:8178)
E( 5829: 5829) 	at java.lang.reflect.Method.invoke(Native Method)
E( 5829: 5829) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E( 5829: 5829) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E( 5829: 5829) Caused by: android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called CREATOR on class org.schabi.newpipe.report.ErrorActivity$ErrorInfo
E( 5829: 5829) 	at android.os.Parcel.readParcelableCreator(Parcel.java:3046)
E( 5829: 5829) 	at android.os.Parcel.readParcelable(Parcel.java:2964)
E( 5829: 5829) 	at android.os.Parcel.readValue(Parcel.java:2866)
E( 5829: 5829) 	at android.os.Parcel.readArrayMapInternal(Parcel.java:3244)
E( 5829: 5829) 	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
E( 5829: 5829) 	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
E( 5829: 5829) 	at android.os.Bundle.getParcelable(Bundle.java:951)
E( 5829: 5829) 	at android.content.Intent.getParcelableExtra(Intent.java:8086)
E( 5829: 5829) 	at org.schabi.newpipe.report.ErrorActivity.onCreate(ErrorActivity.java:21)
E( 5829: 5829) 	at android.app.Activity.performCreate(Activity.java:8086)
E( 5829: 5829) 	at android.app.Activity.performCreate(Activity.java:8074)
E( 5829: 5829) 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
E( 5829: 5829) 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
E( 5829: 5829) 	... 11 more

**Comment by XiangRongLin** [comment]
If i remember correctly bandcamp is a feature that was added afterwards and was not present in the official v0.19.8

This means i would need to also port over the changes from the newer NewPipe version which i am not going to do. I'm only updating the extractor version, meaning there will only be bug fixes

**Comment by Dilmen** [comment]
Maybe should hide Bandcamp?

**Comment by kubo6472** [comment]
> Maybe should hide Bandcamp?

Just tested bandcamp and works for me no problem. Also I think those are loaded dynamically from the extractor, so it's not really possible to hide them WO some workaround like filtering. Not sure, I am a Java beginner.

**Comment by Dilmen** [comment]
> > Maybe should hide Bandcamp?
> 
> Just tested bandcamp and works for me no problem. Also I think those are loaded dynamically from the extractor, so it's not really possible to hide them WO some workaround like filtering. Not sure, I am a Java beginner.

After installing some version after 21.1.1, it showed an error report, and it showed that the UI type error, and not an extractor (GitHub does not insert a screenshot) 

Maybe create Activity and from him go to settings or mainActivity?

report:
> {"user_action":"ui error","request":"App crash, UI failure","content_language":"ru","content_country":"GB","app_language":"ru_RU","service":"none","package":"org.schabi.newpipe.preunified","version":"0.21.14","os":"Linux HONOR/JSN-L21RU","time":"2022-03-15 18:39","exceptions":["android.content.res.Resources$NotFoundException: Resource ID #0x0\n\tat android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:299)\n\tat android.content.res.Resources.getValue(Resources.java:1468)\n\tat androidx.appcompat.widget.ResourceManagerInternal.createDrawableIfNeeded(ResourceManagerInternal.java:176)\n\tat androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:141)\n\tat androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)\n\tat androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:104)\n\tat com.google.android.material.tabs.TabLayout$Tab.setIcon(TabLayout.java:1968)\n\tat org.schabi.newpipe.fragments.MainFragment.updateTabsIconAndDescription(MainFragment.java:192)\n\tat org.schabi.newpipe.fragments.MainFragment.setupTabs(MainFragment.java:181)\n\tat org.schabi.newpipe.fragments.MainFragment.initViews(MainFragment.java:101)\n\tat org.schabi.newpipe.BaseFragment.onViewCreated(BaseFragment.java:71)\n\tat androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)\n\tat androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)\n\tat androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)\n\tat androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)\n\tat androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)\n\tat androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)\n\tat androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)\n\tat androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)\n\tat androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)\n\tat androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)\n\tat androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2629)\n\tat androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)\n\tat androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)\n\tat androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)\n\tat androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)\n\tat android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1440)\n\tat android.app.Activity.performStart(Activity.java:8109)\n\tat android.app.ActivityThread.handleStartActivity(ActivityThread.java:3806)\n\tat android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)\n\tat android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)\n\tat android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)\n\tat android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)\n\tat android.os.Handler.dispatchMessage(Handler.java:107)\n\tat android.os.Looper.loop(Looper.java:213)\n\tat android.app.ActivityThread.main(ActivityThread.java:8178)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)\n"],"user_comment":""}
