### ISSUE TITLE
Very Frequent UI Crash OutOfMemory Error

### ISSUE THREAD

**Issue by Pratham-Chauhan** [XiangRongLin/NewPipe-preuinified#4]
its very annoying bug in newpipe legacy. don't get me wrong, I  appreciate your work. but

this app crash every few minute. this is the only reason I stop using this app before. I use old Samsung galaxy dual core device. the preunified is the only one working fine for me. error occur anytime in between the app, mostly when exiting video or going back to main screen after searching, or clicking on channel to see the videos.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ en-GB
* __Service:__ none
* __Version:__ 0.21.2
* __OS:__ Linux Android 4.1.2 - 16

<details><summary><b>Crash log</b></summary><p>

```
java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:636)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:484)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:813)
	at android.content.res.Resources.loadDrawable(Resources.java:2822)
	at android.content.res.Resources.getDrawable(Resources.java:1522)
	at androidx.appcompat.widget.ResourcesWrapper.getDrawable(ResourcesWrapper.java:130)
	at androidx.appcompat.widget.TintResources.getDrawable(TintResources.java:46)
	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:456)
	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:144)
	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)
	at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:104)
	at androidx.appcompat.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:86)
	at androidx.appcompat.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:94)
	at org.schabi.newpipelegacy.MainActivity.onResume(MainActivity.java:469)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1199)
	at android.app.Activity.performResume(Activity.java:5277)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2633)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2671)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4960)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
	at dalvik.system.NativeStart.main(Native Method)

```
</p></details>
<hr>

**Comment by XiangRongLin** [comment]
I don't think I can help you here. From the error message it looks like you phone is running out of memory while loading thumbnails. You could disable them in the "content" setting

**Comment by Pratham-Chauhan** [comment]
yes, I think it may help but ruin the experience. my device has 250+ mb free memory in ram. I want to point out here that I can run other heavy apps fine without any memory issue like Firefox or some games.
I think this app don't manage memory properly (as it only take max 50 mb). I know devs are working hard to make their app stable. I understand that.

So, for now I use skytube that work fine (and load thumbnails without crash)

![221051912230845](https://user-images.githubusercontent.com/33632299/118770947-8bd16980-b89f-11eb-9863-5d321d0120fb.png)
![20210519123809008](https://user-images.githubusercontent.com/33632299/118771005-9ee43980-b89f-11eb-9bc7-fccf956589a9.png)

**Comment by ShareASmile** [comment]
This error occures frequently even with Thumbnails disabled, [comments & Lock screen video thumbnail also disabled] on Samsung Core GTi8262 Jelly Bean. All preinstalled Google, Samsung inbuilt bloatware apps disabled, Force Stopped. 380MB memory free out of Total RAM of 842MB.

This occured after 25 minutes of use after watching three yt videos in 360p Mpeg4 and pressing device back button. Fresh installation of Legacy preunified v0.21.3 on Freshly Factory Reset Phone. No other user apps installed yet.

Seems bit harsh on device..
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.21.3
* __OS:__ Linux Android 4.1.2 - 16
<details><summary><b>Crash log </b></summary><p>

```
java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:636)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:484)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:813)
	at android.content.res.Resources.loadDrawable(Resources.java:2822)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
	at android.widget.ImageView.<init>(ImageView.java:126)
	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:72)
	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
	at androidx.appcompat.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:187)
	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:107)
	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1407)
	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:681)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at org.schabi.newpipelegacy.fragments.list.channel.ChannelFragment.getListHeader(ChannelFragment.java:158)
	at org.schabi.newpipelegacy.fragments.list.BaseListFragment.initViews(BaseListFragment.java:247)
	at org.schabi.newpipelegacy.fragments.list.BaseListInfoFragment.initViews(BaseListInfoFragment.java:39)
	at org.schabi.newpipelegacy.BaseFragment.onViewCreated(BaseFragment.java:71)
	at org.schabi.newpipelegacy.fragments.BaseStateFragment.onViewCreated(BaseStateFragment.java:56)
	at org.schabi.newpipelegacy.fragments.list.channel.ChannelFragment.onViewCreated(ChannelFragment.java:135)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.BackStackRecord.executePopOps(BackStackRecord.java:510)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2166)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
	at androidx.fragment.app.FragmentManager.popBackStackImmediate(FragmentManager.java:658)
	at androidx.fragment.app.FragmentManager.popBackStackImmediate(FragmentManager.java:569)
	at androidx.fragment.app.FragmentManager.handleOnBackPressed(FragmentManager.java:541)
	at androidx.fragment.app.FragmentManager$1.handleOnBackPressed(FragmentManager.java:350)
	at androidx.activity.OnBackPressedDispatcher.onBackPressed(OnBackPressedDispatcher.java:192)
	at androidx.activity.ComponentActivity.onBackPressed(ComponentActivity.java:314)
	at org.schabi.newpipelegacy.MainActivity.onBackPressed(MainActivity.java:549)
	at android.app.Activity.onKeyUp(Activity.java:2193)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2739)
	at androidx.core.view.KeyEventDispatcher.activitySuperDispatchKeyEventPre28(KeyEventDispatcher.java:137)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:87)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:133)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:558)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2814)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2071)
	at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:3992)
	at android.view.ViewRootImpl.handleImeFinishedEvent(ViewRootImpl.java:3940)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3060)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4960)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
	at dalvik.system.NativeStart.main(Native Method)

```
</details>
<hr>

**Comment by XiangRongLin** [comment]
Then I don't really know. Like i said in the issue linked the about section, i don't plan to do any real development here. You would have to hope that someone picks up https://github.com/TeamNewPipe/NewPipe-legacy again and solves it there
