### ISSUE TITLE
Can't open any video in 0.21.7+

### ISSUE THREAD

**Issue by SpazMahTazz** [XiangRongLin/NewPipe-preuinified#6]
### Version

-Latest (0.21.7+)

### Steps to reproduce the bug

Click on any video, any at all.

### Expected behavior

Open the video
### Actual behaviour

Newpipe crashes and shows the error report (below)

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=xP9A0oH-6mw
* __Content Country:__ AU
* __Content Language:__ en
* __App Language:__ en_AU
* __Service:__ YouTube
* __Version:__ 0.21.7+
* __OS:__ Linux Android 8.1.0 - 27
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
 at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)
 at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
 at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
 at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:117)
 at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$YTHJjScxCJNO1LTCqs3IKy35iyY.call(Unknown Source:4)
 at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
 at io.reactivex.Single.subscribe(Single.java:3666)
 at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
 at io.reactivex.Single.subscribe(Single.java:3666)
 at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
 at io.reactivex.Maybe.subscribe(Maybe.java:4290)
 at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
 at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
 at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
 at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
 at io.reactivex.Flowable.subscribe(Flowable.java:14935)
 at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
 at io.reactivex.Maybe.subscribe(Maybe.java:4290)
 at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
 at io.reactivex.Single.subscribe(Single.java:3666)
 at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
 at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
 at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
 at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
 at java.lang.Thread.run(Thread.java:764)

```
</details>
<hr>

**Comment by XiangRongLin** [comment]
Noted, see https://github.com/TeamNewPipe/NewPipe/pull/6792 for any updates

**Comment by nbmrjuhneibkr** [comment]
This release needs to be pulled immediately, it makes the app completely unusable, and there's no way to roll back without going through the backup/uninstall/reinstall/restore procedure.

**Comment by XiangRongLin** [comment]
new version out
